type Id = string | number;

export const adminEndpoints = {
    users: {
        list: "/api/admin/users",
        create: "/api/admin/users",
        show: (id: Id) => `/api/admin/users/${id}`,
        update: (id: Id) => `/api/admin/users/${id}`,
        delete: (id: Id) => `/api/admin/users/${id}`,
        changePassword: (id: Id) => `/api/admin/users/${id}/password`,
        assignRoles: (id: Id) => `/api/admin/users/${id}/roles`,
    },
    posts: {
        list: "/api/admin/posts",
        create: "/api/admin/posts",
        show: (id: Id) => `/api/admin/posts/${id}`,
        update: (id: Id) => `/api/admin/posts/${id}`,
        delete: (id: Id) => `/api/admin/posts/${id}`,
        stats: (id: Id) => `/api/admin/posts/${id}/stats`,
        overview: "/api/admin/posts/statistics/overview",
    },
    postCategories: {
        list: "/api/admin/post-categories",
        create: "/api/admin/post-categories",
        show: (id: Id) => `/api/admin/post-categories/${id}`,
        update: (id: Id) => `/api/admin/post-categories/${id}`,
        delete: (id: Id) => `/api/admin/post-categories/${id}`,
    },
    postTags: {
        list: "/api/admin/post-tags",
        create: "/api/admin/post-tags",
        show: (id: Id) => `/api/admin/post-tags/${id}`,
        update: (id: Id) => `/api/admin/post-tags/${id}`,
        delete: (id: Id) => `/api/admin/post-tags/${id}`,
    },
    roles: {
        list: "/api/admin/roles",
        simple: "/api/admin/roles/simple",
        create: "/api/admin/roles",
        show: (id: Id) => `/api/admin/roles/${id}`,
        update: (id: Id) => `/api/admin/roles/${id}`,
        delete: (id: Id) => `/api/admin/roles/${id}`,
        assignPermissions: (id: Id) => `/api/admin/roles/${id}/permissions`,
    },
    permissions: {
        list: "/api/admin/permissions",
        simple: "/api/admin/permissions/simple",
        create: "/api/admin/permissions",
        show: (id: Id) => `/api/admin/permissions/${id}`,
        update: (id: Id) => `/api/admin/permissions/${id}`,
        delete: (id: Id) => `/api/admin/permissions/${id}`,
    },
    groups: {
        list: "/api/admin/groups",
        create: "/api/admin/groups",
        show: (id: Id) => `/api/admin/groups/${id}`,
        update: (id: Id) => `/api/admin/groups/${id}`,
        delete: (id: Id) => `/api/admin/groups/${id}`,
        members: {
            list: (groupId: Id) => `/api/groups/${groupId}/members`,
            add: (groupId: Id) => `/api/groups/${groupId}/members`,
            updateRoles: (groupId: Id, memberId: Id) => `/api/groups/${groupId}/members/${memberId}/roles`,
            remove: (groupId: Id, memberId: Id) => `/api/groups/${groupId}/members/${memberId}`,
        },
    },
    aboutSections: {
        list: "/api/admin/about-sections",
        create: "/api/admin/about-sections",
        show: (id: Id) => `/api/admin/about-sections/${id}`,
        update: (id: Id) => `/api/admin/about-sections/${id}`,
        delete: (id: Id) => `/api/admin/about-sections/${id}`,
    },
    projects: {
        list: "/api/admin/projects",
        create: "/api/admin/projects",
        show: (id: Id) => `/api/admin/projects/${id}`,
        update: (id: Id) => `/api/admin/projects/${id}`,
        delete: (id: Id) => `/api/admin/projects/${id}`,
    },
    gallery: {
        list: "/api/admin/gallery",
        create: "/api/admin/gallery",
        show: (id: Id) => `/api/admin/gallery/${id}`,
        update: (id: Id) => `/api/admin/gallery/${id}`,
        delete: (id: Id) => `/api/admin/gallery/${id}`,
    },
    partners: {
        list: "/api/admin/partners",
        create: "/api/admin/partners",
        show: (id: Id) => `/api/admin/partners/${id}`,
        update: (id: Id) => `/api/admin/partners/${id}`,
        delete: (id: Id) => `/api/admin/partners/${id}`,
    },
    certificates: {
        list: "/api/admin/certificates",
        create: "/api/admin/certificates",
        show: (id: Id) => `/api/admin/certificates/${id}`,
        update: (id: Id) => `/api/admin/certificates/${id}`,
        delete: (id: Id) => `/api/admin/certificates/${id}`,
    },
    faqs: {
        list: "/api/admin/faqs",
        create: "/api/admin/faqs",
        show: (id: Id) => `/api/admin/faqs/${id}`,
        update: (id: Id) => `/api/admin/faqs/${id}`,
        delete: (id: Id) => `/api/admin/faqs/${id}`,
    },
    testimonials: {
        list: "/api/admin/testimonials",
        create: "/api/admin/testimonials",
        show: (id: Id) => `/api/admin/testimonials/${id}`,
        update: (id: Id) => `/api/admin/testimonials/${id}`,
        delete: (id: Id) => `/api/admin/testimonials/${id}`,
        toggleFeatured: (id: Id) => `/api/admin/testimonials/${id}/featured`,
    },
    staff: {
        list: "/api/admin/staff",
        create: "/api/admin/staff",
        show: (id: Id) => `/api/admin/staff/${id}`,
        update: (id: Id) => `/api/admin/staff/${id}`,
        delete: (id: Id) => `/api/admin/staff/${id}`,
    },
    banners: {
        list: "/api/admin/banners",
        create: "/api/admin/banners",
        show: (id: Id) => `/api/admin/banners/${id}`,
        update: (id: Id) => `/api/admin/banners/${id}`,
        delete: (id: Id) => `/api/admin/banners/${id}`,
        updateStatus: (id: Id) => `/api/admin/banners/${id}/status`,
        updateSortOrder: (id: Id) => `/api/admin/banners/${id}/sort-order`,
        restore: (id: Id) => `/api/admin/banners/${id}/restore`,
        getByLocation: (locationCode: string) => `/api/admin/banners/location/${locationCode}`,
    },
    bannerLocations: {
        list: "/api/admin/banner-locations",
        create: "/api/admin/banner-locations",
        show: (id: Id) => `/api/admin/banner-locations/${id}`,
        update: (id: Id) => `/api/admin/banner-locations/${id}`,
        delete: (id: Id) => `/api/admin/banner-locations/${id}`,
        updateStatus: (id: Id) => `/api/admin/banner-locations/${id}/status`,
        restore: (id: Id) => `/api/admin/banner-locations/${id}/restore`,
        getByCode: (code: string) => `/api/admin/banner-locations/code/${code}`,
    },
    contexts: {
        list: "/api/admin/contexts",
        create: "/api/admin/contexts",
        show: (id: Id) => `/api/admin/contexts/${id}`,
        update: (id: Id) => `/api/admin/contexts/${id}`,
        delete: (id: Id) => `/api/admin/contexts/${id}`,
    },
    paymentMethods: {
        list: "/api/admin/payment-methods",
        create: "/api/admin/payment-methods",
        show: (id: Id) => `/api/admin/payment-methods/${id}`,
        update: (id: Id) => `/api/admin/payment-methods/${id}`,
        delete: (id: Id) => `/api/admin/payment-methods/${id}`,
        updateStatus: (id: Id) => `/api/admin/payment-methods/${id}/status`,
    },
    warehouses: {
        list: "/api/admin/warehouses",
        simple: "/api/admin/warehouses/simple",
        create: "/api/admin/warehouses",
        show: (id: Id) => `/api/admin/warehouses/${id}`,
        update: (id: Id) => `/api/admin/warehouses/${id}`,
        delete: (id: Id) => `/api/admin/warehouses/${id}`,
        inventory: (id: Id) => `/api/admin/warehouses/${id}/inventory`,
        updateInventory: "/api/admin/warehouses/inventory/update",
        transfers: {
            create: "/api/admin/warehouses/transfers",
            list: "/api/admin/warehouses/transfers/list",
            approve: (id: Id) => `/api/admin/warehouses/transfers/${id}/approve`,
            complete: (id: Id) => `/api/admin/warehouses/transfers/${id}/complete`,
            cancel: (id: Id) => `/api/admin/warehouses/transfers/${id}/cancel`,
        },
    },
    productVariants: {
        list: "/api/admin/product-variants",
        simple: "/api/admin/product-variants/simple",
        byProduct: (productId: Id) => `/api/admin/product-variants/product/${productId}`,
        search: "/api/admin/product-variants/search",
        bySku: (sku: string) => `/api/admin/product-variants/sku/${encodeURIComponent(sku)}`,
        create: "/api/admin/product-variants",
        show: (id: Id) => `/api/admin/product-variants/${id}`,
        update: (id: Id) => `/api/admin/product-variants/${id}`,
        delete: (id: Id) => `/api/admin/product-variants/${id}`,
        restore: (id: Id) => `/api/admin/product-variants/${id}/restore`,
    },
    contacts: {
        list: "/api/admin/contacts",
        create: "/api/admin/contacts",
        show: (id: Id) => `/api/admin/contacts/${id}`,
        update: (id: Id) => `/api/admin/contacts/${id}`,
        delete: (id: Id) => `/api/admin/contacts/${id}`,
        reply: (id: Id) => `/api/admin/contacts/${id}/reply`,
        markAsRead: (id: Id) => `/api/admin/contacts/${id}/read`,
        close: (id: Id) => `/api/admin/contacts/${id}/close`,
    },
    contentTemplates: {
        list: "/api/admin/content-templates",
        create: "/api/admin/content-templates",
        show: (id: Id) => `/api/admin/content-templates/${id}`,
        update: (id: Id) => `/api/admin/content-templates/${id}`,
        delete: (id: Id) => `/api/admin/content-templates/${id}`,
        test: (id: Id) => `/api/admin/content-templates/${id}/test`,
    },
    menus: {
        list: "/api/admin/menus",
        create: "/api/admin/menus",
        show: (id: Id) => `/api/admin/menus/${id}`,
        update: (id: Id) => `/api/admin/menus/${id}`,
        delete: (id: Id) => `/api/admin/menus/${id}`,
        tree: "/api/admin/menus/tree",
        restore: (id: Id) => `/api/admin/menus/${id}/restore`,
    },
    userMenus: {
        list: "/api/admin/user/menus",
    },
    enums: {
        all: "/api/enums",
        byName: (type: string) => `/api/enums/${type}`,
    },
    systemConfigs: {
        getByGroup: (group: string) => `/api/admin/system-configs/${group}`,
        update: (group: string) => `/api/admin/system-configs/${group}`,
    },
    postComments: {
        list: "/api/admin/post-comments",
        updateStatus: (id: Id) => `/api/admin/post-comments/${id}/status`,
        delete: (id: Id) => `/api/admin/post-comments/${id}`,
    },
    comicComments: {
        list: "/api/admin/comic-comments",
        statistics: "/api/admin/comic-comments/statistics",
        update: (id: Id) => `/api/admin/comic-comments/${id}`,
        delete: (id: Id) => `/api/admin/comic-comments/${id}`,
        updateStatus: (id: Id) => `/api/admin/comic-comments/${id}/status`,
    },
    shippingMethods: {
        list: "/api/admin/shipping-methods",
        simple: "/api/admin/shipping-methods/simple",
        active: "/api/admin/shipping-methods/active",
        create: "/api/admin/shipping-methods",
        show: (id: Id) => `/api/admin/shipping-methods/${id}`,
        update: (id: Id) => `/api/admin/shipping-methods/${id}`,
        delete: (id: Id) => `/api/admin/shipping-methods/${id}`,
        updateStatus: (id: Id) => `/api/admin/shipping-methods/${id}/status`,
        restore: (id: Id) => `/api/admin/shipping-methods/${id}/restore`,
        getByCode: (code: string) => `/api/admin/shipping-methods/code/${code}`,
    },
    productCategories: {
        list: "/api/admin/product-categories",
        simple: "/api/admin/product-categories/simple",
        tree: "/api/admin/product-categories/tree",
        root: "/api/admin/product-categories/root",
        children: (id: Id) => `/api/admin/product-categories/${id}/children`,
        create: "/api/admin/product-categories",
        show: (id: Id) => `/api/admin/product-categories/${id}`,
        update: (id: Id) => `/api/admin/product-categories/${id}`,
        delete: (id: Id) => `/api/admin/product-categories/${id}`,
        restore: (id: Id) => `/api/admin/product-categories/${id}/restore`,
    },
    productAttributes: {
        list: "/api/admin/product-attributes",
        simple: "/api/admin/product-attributes/simple",
        create: "/api/admin/product-attributes",
        show: (id: Id) => `/api/admin/product-attributes/${id}`,
        update: (id: Id) => `/api/admin/product-attributes/${id}`,
        delete: (id: Id) => `/api/admin/product-attributes/${id}`,
    },
    productAttributeValues: {
        list: "/api/admin/product-attribute-values",
        simple: "/api/admin/product-attribute-values/simple",
        byAttribute: (attributeId: Id) => `/api/admin/product-attribute-values/attribute/${attributeId}`,
        create: "/api/admin/product-attribute-values",
        show: (id: Id) => `/api/admin/product-attribute-values/${id}`,
        update: (id: Id) => `/api/admin/product-attribute-values/${id}`,
        delete: (id: Id) => `/api/admin/product-attribute-values/${id}`,
        restore: (id: Id) => `/api/admin/product-attribute-values/${id}/restore`,
    },
    products: {
        list: "/api/admin/products",
        create: "/api/admin/products",
        show: (id: Id) => `/api/admin/products/${id}`,
        update: (id: Id) => `/api/admin/products/${id}`,
        delete: (id: Id) => `/api/admin/products/${id}`,
    },
    productDigitalAssets: {
        list: "/api/admin/ecommerce/product-digital-assets",
        bulkImport: "/api/admin/ecommerce/product-digital-assets/bulk-import",
        delete: (id: Id) => `/api/admin/ecommerce/product-digital-assets/${id}`,
        update: (id: Id) => `/api/admin/ecommerce/product-digital-assets/${id}`,
    },
    orders: {
        list: "/api/admin/orders",
        show: (id: Id) => `/api/admin/orders/${id}`,
        updateStatus: (id: Id) => `/api/admin/orders/${id}/status`,
        cancel: (id: Id) => `/api/admin/orders/${id}/cancel`,
    },
    coupons: {
        list: "/api/admin/coupons",
        create: "/api/admin/coupons",
        show: (id: Id) => `/api/admin/coupons/${id}`,
        update: (id: Id) => `/api/admin/coupons/${id}`,
        delete: (id: Id) => `/api/admin/coupons/${id}`,
    },
    warehouseImports: {
        list: "/api/admin/warehouse-imports",
        create: "/api/admin/warehouses/imports",
        show: (id: Id) => `/api/admin/warehouse-imports/${id}`,
        approve: (id: Id) => `/api/admin/warehouse-imports/${id}/approve`,
        cancel: (id: Id) => `/api/admin/warehouse-imports/${id}/cancel`,
    },
    warehouseExports: {
        list: "/api/admin/warehouse-exports",
        create: "/api/admin/warehouses/exports",
        show: (id: Id) => `/api/admin/warehouse-exports/${id}`,
        approve: (id: Id) => `/api/admin/warehouse-exports/${id}/approve`,
        cancel: (id: Id) => `/api/admin/warehouse-exports/${id}/cancel`,
    },
    comicCategories: {
        list: "/api/admin/comic-categories",
        create: "/api/admin/comic-categories",
        show: (id: Id) => `/api/admin/comic-categories/${id}`,
        update: (id: Id) => `/api/admin/comic-categories/${id}`,
        delete: (id: Id) => `/api/admin/comic-categories/${id}`,
    },
    comics: {
        list: "/api/admin/comics",
        create: "/api/admin/comics",
        show: (id: Id) => `/api/admin/comics/${id}`,
        update: (id: Id) => `/api/admin/comics/${id}`,
        delete: (id: Id) => `/api/admin/comics/${id}`,
        uploadCover: (id: Id) => `/api/admin/comics/${id}/cover`,
    },
    chapters: {
        list: "/api/admin/chapters",
        create: "/api/admin/chapters",
        show: (id: Id) => `/api/admin/chapters/${id}`,
        update: (id: Id) => `/api/admin/chapters/${id}`,
        delete: (id: Id) => `/api/admin/chapters/${id}`,
        uploadPages: (id: Id) => `/api/admin/chapters/${id}/pages`,
        updatePages: (id: Id) => `/api/admin/chapters/${id}/pages`,
    },
    comicStats: {
        overview: "/api/admin/comic-stats/overview",
        topViewed: "/api/admin/comic-stats/top-viewed",
        topFollowed: "/api/admin/comic-stats/top-followed",
        trending: "/api/admin/comic-stats/trending",
    },
    analytics: {
        dashboard: "/api/admin/stats/dashboard",
        comics: "/api/admin/stats/comics",
        views: "/api/admin/stats/views",
    },
    reviews: {
        list: "/api/admin/reviews",
        create: "/api/admin/reviews",
        statistics: "/api/admin/reviews/statistics",
        show: (id: Id) => `/api/admin/reviews/${id}`,
        update: (id: Id) => `/api/admin/reviews/${id}`,
        delete: (id: Id) => `/api/admin/reviews/${id}`,
    },
} as const;





