type Id = string | number;

export const adminEndpoints = {
    users: {
        list: "/api/admin/users",
        create: "/api/admin/users",
        show: (id: Id) => `/api/admin/users/${id}`,
        update: (id: Id) => `/api/admin/users/${id}`,
        delete: (id: Id) => `/api/admin/users/${id}`,
        changePassword: (id: Id) => `/api/admin/users/${id}/password`,
        assignRoles: (id: Id) => `/api/admin/users/${id}/roles`,
    },
    posts: {
        list: "/api/admin/posts",
        create: "/api/admin/posts",
        show: (id: Id) => `/api/admin/posts/${id}`,
        update: (id: Id) => `/api/admin/posts/${id}`,
        delete: (id: Id) => `/api/admin/posts/${id}`,
        stats: (id: Id) => `/api/admin/posts/${id}/stats`,
        overview: "/api/admin/posts/statistics/overview",
    },
    postCategories: {
        list: "/api/admin/post-categories",
        create: "/api/admin/post-categories",
        show: (id: Id) => `/api/admin/post-categories/${id}`,
        update: (id: Id) => `/api/admin/post-categories/${id}`,
        delete: (id: Id) => `/api/admin/post-categories/${id}`,
    },
    postTags: {
        list: "/api/admin/post-tags",
        create: "/api/admin/post-tags",
        show: (id: Id) => `/api/admin/post-tags/${id}`,
        update: (id: Id) => `/api/admin/post-tags/${id}`,
        delete: (id: Id) => `/api/admin/post-tags/${id}`,
    },
    roles: {
        list: "/api/admin/roles",
        simple: "/api/admin/roles/simple",
        create: "/api/admin/roles",
        show: (id: Id) => `/api/admin/roles/${id}`,
        update: (id: Id) => `/api/admin/roles/${id}`,
        delete: (id: Id) => `/api/admin/roles/${id}`,
        assignPermissions: (id: Id) => `/api/admin/roles/${id}/permissions`,
    },
    permissions: {
        list: "/api/admin/permissions",
        simple: "/api/admin/permissions/simple",
        create: "/api/admin/permissions",
        show: (id: Id) => `/api/admin/permissions/${id}`,
        update: (id: Id) => `/api/admin/permissions/${id}`,
        delete: (id: Id) => `/api/admin/permissions/${id}`,
    },
    groups: {
        list: "/api/admin/groups",
        create: "/api/admin/groups",
        show: (id: Id) => `/api/admin/groups/${id}`,
        update: (id: Id) => `/api/admin/groups/${id}`,
        delete: (id: Id) => `/api/admin/groups/${id}`,
        members: {
            list: (groupId: Id) => `/api/groups/${groupId}/members`,
            add: (groupId: Id) => `/api/groups/${groupId}/members`,
            updateRoles: (groupId: Id, memberId: Id) => `/api/groups/${groupId}/members/${memberId}/roles`,
            remove: (groupId: Id, memberId: Id) => `/api/groups/${groupId}/members/${memberId}`,
        },
    },
    aboutSections: {
        list: "/api/admin/about-sections",
        create: "/api/admin/about-sections",
        show: (id: Id) => `/api/admin/about-sections/${id}`,
        update: (id: Id) => `/api/admin/about-sections/${id}`,
        delete: (id: Id) => `/api/admin/about-sections/${id}`,
    },
    projects: {
        list: "/api/admin/projects",
        create: "/api/admin/projects",
        show: (id: Id) => `/api/admin/projects/${id}`,
        update: (id: Id) => `/api/admin/projects/${id}`,
        delete: (id: Id) => `/api/admin/projects/${id}`,
    },
    gallery: {
        list: "/api/admin/gallery",
        create: "/api/admin/gallery",
        show: (id: Id) => `/api/admin/gallery/${id}`,
        update: (id: Id) => `/api/admin/gallery/${id}`,
        delete: (id: Id) => `/api/admin/gallery/${id}`,
    },
    partners: {
        list: "/api/admin/partners",
        create: "/api/admin/partners",
        show: (id: Id) => `/api/admin/partners/${id}`,
        update: (id: Id) => `/api/admin/partners/${id}`,
        delete: (id: Id) => `/api/admin/partners/${id}`,
    },
    certificates: {
        list: "/api/admin/certificates",
        create: "/api/admin/certificates",
        show: (id: Id) => `/api/admin/certificates/${id}`,
        update: (id: Id) => `/api/admin/certificates/${id}`,
        delete: (id: Id) => `/api/admin/certificates/${id}`,
    },
    faqs: {
        list: "/api/admin/faqs",
        create: "/api/admin/faqs",
        show: (id: Id) => `/api/admin/faqs/${id}`,
        update: (id: Id) => `/api/admin/faqs/${id}`,
        delete: (id: Id) => `/api/admin/faqs/${id}`,
    },
    testimonials: {
        list: "/api/admin/testimonials",
        create: "/api/admin/testimonials",
        show: (id: Id) => `/api/admin/testimonials/${id}`,
        update: (id: Id) => `/api/admin/testimonials/${id}`,
        delete: (id: Id) => `/api/admin/testimonials/${id}`,
        toggleFeatured: (id: Id) => `/api/admin/testimonials/${id}/featured`,
    },
    staff: {
        list: "/api/admin/staff",
        create: "/api/admin/staff",
        show: (id: Id) => `/api/admin/staff/${id}`,
        update: (id: Id) => `/api/admin/staff/${id}`,
        delete: (id: Id) => `/api/admin/staff/${id}`,
    },
    banners: {
        list: "/api/admin/banners",
        create: "/api/admin/banners",
        show: (id: Id) => `/api/admin/banners/${id}`,
        update: (id: Id) => `/api/admin/banners/${id}`,
        delete: (id: Id) => `/api/admin/banners/${id}`,
        updateStatus: (id: Id) => `/api/admin/banners/${id}/status`,
        updateSortOrder: (id: Id) => `/api/admin/banners/${id}/sort-order`,
        restore: (id: Id) => `/api/admin/banners/${id}/restore`,
        getByLocation: (locationCode: string) => `/api/admin/banners/location/${locationCode}`,
    },
    bannerLocations: {
        list: "/api/admin/banner-locations",
        create: "/api/admin/banner-locations",
        show: (id: Id) => `/api/admin/banner-locations/${id}`,
        update: (id: Id) => `/api/admin/banner-locations/${id}`,
        delete: (id: Id) => `/api/admin/banner-locations/${id}`,
        updateStatus: (id: Id) => `/api/admin/banner-locations/${id}/status`,
        restore: (id: Id) => `/api/admin/banner-locations/${id}/restore`,
        getByCode: (code: string) => `/api/admin/banner-locations/code/${code}`,
    },
    contexts: {
        list: "/api/admin/contexts",
        create: "/api/admin/contexts",
        show: (id: Id) => `/api/admin/contexts/${id}`,
        update: (id: Id) => `/api/admin/contexts/${id}`,
        delete: (id: Id) => `/api/admin/contexts/${id}`,
    },
    paymentMethods: {
        list: "/api/admin/payment-methods",
        create: "/api/admin/payment-methods",
        show: (id: Id) => `/api/admin/payment-methods/${id}`,
        update: (id: Id) => `/api/admin/payment-methods/${id}`,
        delete: (id: Id) => `/api/admin/payment-methods/${id}`,
        updateStatus: (id: Id) => `/api/admin/payment-methods/${id}/status`,
    },
    warehouses: {
        list: "/api/admin/warehouses",
        create: "/api/admin/warehouses",
        show: (id: Id) => `/api/admin/warehouses/${id}`,
        update: (id: Id) => `/api/admin/warehouses/${id}`,
        delete: (id: Id) => `/api/admin/warehouses/${id}`,
        inventory: (id: Id) => `/api/admin/warehouses/${id}/inventory`,
        updateInventory: "/api/admin/warehouses/inventory/update",
    },
    contacts: {
        list: "/api/admin/contacts",
        create: "/api/admin/contacts",
        show: (id: Id) => `/api/admin/contacts/${id}`,
        update: (id: Id) => `/api/admin/contacts/${id}`,
        delete: (id: Id) => `/api/admin/contacts/${id}`,
        reply: (id: Id) => `/api/admin/contacts/${id}/reply`,
        markAsRead: (id: Id) => `/api/admin/contacts/${id}/read`,
        close: (id: Id) => `/api/admin/contacts/${id}/close`,
    },
    contentTemplates: {
        list: "/api/admin/content-templates",
        create: "/api/admin/content-templates",
        show: (id: Id) => `/api/admin/content-templates/${id}`,
        update: (id: Id) => `/api/admin/content-templates/${id}`,
        delete: (id: Id) => `/api/admin/content-templates/${id}`,
        test: (id: Id) => `/api/admin/content-templates/${id}/test`,
    },
    menus: {
        list: "/api/admin/menus",
        create: "/api/admin/menus",
        show: (id: Id) => `/api/admin/menus/${id}`,
        update: (id: Id) => `/api/admin/menus/${id}`,
        delete: (id: Id) => `/api/admin/menus/${id}`,
        tree: "/api/admin/menus/tree",
        restore: (id: Id) => `/api/admin/menus/${id}/restore`,
    },
    userMenus: {
        list: "/api/admin/user/menus",
    },
    enums: {
        all: "/api/enums",
        byName: (type: string) => `/api/enums/${type}`,
    },
    systemConfigs: {
        getByGroup: (group: string) => `/api/admin/system-configs/${group}`,
        update: (group: string) => `/api/admin/system-configs/${group}`,
    },
    postComments: {
        list: "/api/admin/post-comments",
        updateStatus: (id: Id) => `/api/admin/post-comments/${id}/status`,
        delete: (id: Id) => `/api/admin/post-comments/${id}`,
    },
    shippingMethods: {
        list: "/api/admin/shipping-methods",
        simple: "/api/admin/shipping-methods/simple",
        active: "/api/admin/shipping-methods/active",
        create: "/api/admin/shipping-methods",
        show: (id: Id) => `/api/admin/shipping-methods/${id}`,
        update: (id: Id) => `/api/admin/shipping-methods/${id}`,
        delete: (id: Id) => `/api/admin/shipping-methods/${id}`,
        updateStatus: (id: Id) => `/api/admin/shipping-methods/${id}/status`,
        restore: (id: Id) => `/api/admin/shipping-methods/${id}/restore`,
        getByCode: (code: string) => `/api/admin/shipping-methods/code/${code}`,
    },
    productCategories: {
        list: "/api/admin/product-categories",
        simple: "/api/admin/product-categories/simple",
        tree: "/api/admin/product-categories/tree",
        root: "/api/admin/product-categories/root",
        children: (id: Id) => `/api/admin/product-categories/${id}/children`,
        create: "/api/admin/product-categories",
        show: (id: Id) => `/api/admin/product-categories/${id}`,
        update: (id: Id) => `/api/admin/product-categories/${id}`,
        delete: (id: Id) => `/api/admin/product-categories/${id}`,
        restore: (id: Id) => `/api/admin/product-categories/${id}/restore`,
    },
    productAttributes: {
        list: "/api/admin/product-attributes",
        create: "/api/admin/product-attributes",
        show: (id: Id) => `/api/admin/product-attributes/${id}`,
        update: (id: Id) => `/api/admin/product-attributes/${id}`,
        delete: (id: Id) => `/api/admin/product-attributes/${id}`,
    },
} as const;

